language: php

notifications:
  email: false
  slack:
    secure: JzGnFqEjxB4v1Pr94rMBRGlwz1ASKPtTUMHlyASnbcWyF/FORbpe7dm/RQFdVbOklzpFZ6ze3OpVRRSrSOfjZSBHLAN0AAczVjO4puIcvy5a9ZqOhpETtkkdJQM56/LYr3O4pFRQ6FO57Tcokq4IeuxdMbWTFnFnlsZjKnHE6m4=

php:
  - 7.0

install: composer install -o

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tests;'
  - mysql tests < tests/Model/Fixture/cars.sql

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
